// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ycrstudbmkbxzgtbnclz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljcnN0dWRibWtieHpndGJuY2x6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODM4NzcsImV4cCI6MjA3MTk1OTg3N30.z_fPL_dupeJ7LMTPMZbJPY-aYeoWGiZrMiwYz7jyIW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});